version: '2'
services:
  bayberry:
    image: erikperkins/bayberry
    restart: on-failure
    environment:
      MIX_ENV: prod
      BAYBERRY_SECRET_KEY_BASE: ${BAYBERRY_SECRET_KEY_BASE}
      BAYBERRY_USERNAME: ${BAYBERRY_USERNAME}
      BAYBERRY_PASSWORD: ${BAYBERRY_PASSWORD}
      BAYBERRY_DATABASE: ${BAYBERRY_DATABASE}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
      REDIS_HOST: storage.datapun.net
      RABBITMQ_HOST: storage.datapun.net
    ports:
      - 80:80
